apiVersion: v1
kind: Service
metadata: 
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels: 
    app: ftps
  name: ftps
spec: 
  ports: 
       - port: 21
         name: ftps-port
       - port: 20
         name: port-ftps
       - port: 31009
         name: ftps-passv-port
       - port: 31010
         name: passv-ftps-port
       - port: 31011
         name: passv-ftps-port1
  selector: 
    app: ftps
  type: LoadBalancer

---
        
apiVersion: apps/v1
kind: Deployment
metadata: 
     labels: 
       app: ftps
     name: ftps
spec: 
     replicas: 1
     selector: 
       matchLabels: 
         app: ftps
     template: 
       metadata: 
         labels: 
           app: ftps
       spec: 
         containers: 
           - image: ftps_service
             name: ftps
             imagePullPolicy: Never
             ports:
              - containerPort: 21
              - containerPort: 31009
              - containerPort: 31010
              - containerPort: 31011
             livenessProbe:
              exec:
                command:
                - sh
                - livness.sh
              initialDelaySeconds: 30
              periodSeconds: 7