apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: mysql
  name: mysql
spec: 
  ports: 
    - port: 3306
  selector: 
    app: mysql
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mysql
  name: mysql
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mysql
  template: 
    metadata: 
      labels: 
        app: mysql
    spec: 
      containers: 
        - image: mysql_service
          name: mysql
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql
              mountPath: /var/lib/mysql
          livenessProbe:
              exec:
                command:
                - sh
                - livness.sh
              initialDelaySeconds: 30
              periodSeconds: 5
      volumes:
            - name: mysql
              persistentVolumeClaim:
                claimName: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi