FROM alpine:latest

# RUN apk add --update nginx openrc
# RUN mkdir -p /tmp/nginx/client-body
# COPY config/nginx.conf /etc/nginx/nginx.conf
# COPY config/default.conf /etc/nginx/conf.d/default.conf
# COPY website /usr/share/nginx/html
# RUN apk add php7 php7-fpm php7-opcache
# RUN apk add php7-gd php7-mysqli php7-zlib php7-curl
EXPOSE  5000
# CMD ["nginx", "-g", "daemon off;"]