apiVersion: v1
kind: Service
metadata: 
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels: 
    app: wordpress
  name: wordpress-service
spec: 
  ports: 
    - port: 5050
      targetPort: 80
  selector: 
    app: wordpress
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: wordpress 
  name: wordpress-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: wordpress
  template: 
    metadata: 
      labels: 
        app: wordpress
    spec: 
      containers: 
        - 
          image: wordpress_service
          name: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          # livenessProbe:
          #     exec:
          #       command:
          #       - /bin/sh
          #       - /startlivness.sh
          #     initialDelaySeconds: 30
          #     periodSeconds: 5